### lOGIN 
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "admin123"
}

### POST new kasir
POST http://localhost:8080/api/v1/kasir
Content-Type: application/json

{
    "name": "Ucup Bin Calucup",
    "email": "kasir2@gmail.com",
    "password": "kasir123"
}

### GET all kasir

GET http://localhost:8080/api/v1/kasir


### GET kasir by id

GET http://localhost:8080/api/v1/kasir/6


### Put kasir by id

PUT http://localhost:8080/api/v1/kasir/4
Content-Type: application/json

{
    "name": "Kasir 5 Updated",
    "email": "kasir3_updated@admin.com",
    "password": "kasir123_updated"
}

### DELETE kasir by id

DELETE http://localhost:8080/api/v1/kasir/3



### PAKET

### POST new paket
POST http://localhost:8080/api/v1/paket
Content-Type: application/json

{
    "nama": "Test New Paket",
    "harga_per_kg": 30000,
    "catatan": "Akan Dihapus"
}

### GET all paket
GET http://localhost:8080/api/v1/paket

### GET all paket, status aktif
GET http://localhost:8080/api/v1/paket/active

### GET paket by id
GET http://localhost:8080/api/v1/paket/12

### PUT paket by id
PUT http://localhost:8080/api/v1/paket/12
Content-Type: application/json

{
    "nama": "Test 2 New Paket",
    "harga_per_kg": 30000,
    "catatan": "Akan Dihapus",
    "status": "NONAKTIF"
}

### DELETE paket by id
DELETE http://localhost:8080/api/v1/paket/12



### PESANAN

### POST new pesanan
POST http://localhost:8080/api/v1/pesanan
Content-Type: application/json

{
    "kasirId": 3,
    "paketId": 1,
    "beratKg": 2,
    "namaPelanggan": "Injil",
    "String": "Customer VIP"
}

### GET all pesanan
GET http://localhost:8080/api/v1/pesanan


### GET pesanan by id
GET http://localhost:8080/api/v1/pesanan/2


### PUT pesanan by id
PUT http://localhost:8080/api/v1/pesanan/2
Content-Type: application/json

{
    "kasirId": 10,
    "paketId": 3,
    "beratKg": 4,
    "namaPelanggan": "Injil (Update)",
    "String": "Customer VI (Update)",
    "status": "DIPROSES"
}

