### lOGIN 
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
    "email": "Awewe@gmail.com",
    "password": "kasir123"
}

### POST new kasir

POST http://localhost:8080/api/v1/kasir
Content-Type: application/json

{
    "name": "Ucup Bin Calucup",
    "email": "admin@admin.com",
    "password": "kasir123"
}

### GET all kasir

GET http://localhost:8080/api/v1/kasir


### GET kasir by id

GET http://localhost:8080/api/v1/kasir/9


### Put kasir by id

PUT http://localhost:8080/api/v1/kasir/5
Content-Type: application/json

{
    "name": "Kasir 2 Updated",
    "email": "kasir2_updated@admin.com",
    "password": "kasir123_updated"
}

### DELETE kasir by id

DELETE http://localhost:8080/api/v1/kasir/1


### PAKET

### POST new paket

POST http://localhost:8080/api/v1/paket
Content-Type: application/json

{
    "nama": "Kecepatan",
    "harga_per_kg": 30000,
    "catatan": "1 Jam"
}

### GET all paket
GET http://localhost:8080/api/v1/paket

### GET paket by id
GET http://localhost:8080/api/v1/paket/3

### PUT paket by id
PUT http://localhost:8080/api/v1/paket/3
Content-Type: application/json

{
    "nama": "Petir",
    "harga_per_kg": 30000,
    "catatan": "1 Jam, Kering, Setrika",
    "status": "AKTIF"
}

### DELETE paket by id
DELETE http://localhost:8080/api/v1/paket/2